import type { Carousel } from "./types";

export const SAMPLE: Carousel = {
  tema: "Estímulo no glúteo (exemplo)",
  cards: [
    { id: "1", layout: "cover", image: "/img/capa.jpg", focalX: 0.5, focalY: 0.2,
      headline: "2 ANOS AGACHANDO E O ESPELHO NÃO **MUDA**", index: "01 / 10" },
    { id: "2", layout: "top", image: "/img/treino.jpg", focalX: 0.5, focalY: 0.25, kicker: "Glúteo",
      headline: "O QUE QUASE TODA MULHER FAZ",
      body: "Você agacha toda semana, aumenta o peso de vez em quando, e mesmo assim o glúteo não responde. A culpa não é sua. É do **estímulo errado**.\n\nAgachar não é a mesma coisa que estimular o glúteo.",
      index: "02 / 10" },
    { id: "3", layout: "bottom", image: "/img/foco.jpg", focalX: 0.5, focalY: 0.45, kicker: "Execução",
      headline: "ONDE O ESTÍMULO SE PERDE",
      body: "No agachamento, boa parte da carga vai pro quadríceps e pra lombar. O glúteo entra, mas raramente como **protagonista**.\n\nSe o objetivo é glúteo, ele precisa ser o foco.",
      index: "03 / 10" },
    { id: "4", layout: "list", kicker: "Faz assim", headline: "PRA O GLÚTEO VIRAR PROTAGONISTA",
      bullets: ["Exercícios de quadril (elevação pélvica, coice)", "Amplitude completa, sem roubar com a lombar", "**Sobrecarga progressiva** semana após semana", "Perto da falha nas últimas séries"],
      index: "04 / 10" },
    { id: "5", layout: "data", image: "/img/espelho.jpg", focalX: 0.55, focalY: 0.4, kicker: "O que importa",
      headline: "NÃO É O NÚMERO DE TREINOS",
      stats: [{ value: "6-8", label: "SEMANAS PRA SENTIR" }, { value: "2x", label: "GLÚTEO POR SEMANA" }, { value: "0", label: "ATALHO QUE FUNCIONA" }],
      body: "Constância bate intensidade. O treino que você **mantém** vence o perfeito que você abandona.",
      index: "05 / 10" },
    { id: "6", layout: "quote", headline: "AGACHAR NÃO É TREINAR **GLÚTEO**", index: "06 / 10" },
    { id: "7", layout: "text", kicker: "A real", headline: "ENTENDE ISSO",
      body: "Seu glúteo responde a estímulo\nSempre respondeu\n\nResultado travado pede **método** repetido por tempo suficiente", index: "07 / 10" },
    { id: "8", layout: "split", image: "/img/conquista.jpg", focalX: 0.5, focalY: 0.4, kicker: "O custo", headline: "TEM PREÇO",
      body: "Constância, paciência e ajustar a execução.\n\nNem todo mundo **sustenta** isso. Quem sustenta, colhe.", index: "08 / 10" },
    { id: "9", layout: "steps", kicker: "O caminho", headline: "COMO O GLÚTEO CRESCE",
      bullets: ["Estímulo certo, no músculo certo", "Sobrecarga progressiva ao longo das semanas", "Recuperação e **constância**"], index: "09 / 10" },
    { id: "10", layout: "moral", image: "/img/foco.jpg", focalX: 0.5, focalY: 0.3,
      body: "No fim é isso\nPara de procurar o treino mágico e o agachamento perfeito\n\nO que constrói é o **estímulo certo, repetido**, mês após mês\nO resto é ruído",
      signoff: "Click no link da bio", index: "10 / 10" },
  ],
};
